<?php
$specificInfo = $block->getSpecificInformation();
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<?= $block->escapeHtml($paymentTitle) ?>

<?php if ($specificInfo) : ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value) : ?>
            <tr>
                <th><?= $block->escapeHtml($label) ?>:</th>
                <td>
                    <?= /* @noEscape */ $value; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml() ?>
