<?php
namespace Iugu\Payment\Block\Checkout\Onepage\Success;

use Iugu\Payment\Model\Ui\ConfigProvider;
use Magento\Checkout\Model\Session;
use Magento\Framework\View\Element\Template\Context;

class BankSlip extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Session
     */
    private $checkoutSession;

    /**
     * @param Context $context
     * @param Session $checkoutSession
     * @param array $data
     */
    public function __construct(
        Context $context,
        Session $checkoutSession,
        array $data = []
    ) {
        $this->checkoutSession = $checkoutSession;
        parent::__construct($context, $data);
    }

    /**
     * @return string
     */
    protected function _toHtml()
    {
        $payment = $this->checkoutSession->getLastRealOrder()->getPayment();
        if ($payment->getMethod() !== ConfigProvider::BS_CODE) {
            return '';
        }
        $additionalInformation = $this->checkoutSession->getLastRealOrder()->getPayment()->getAdditionalInformation();

        $this->addData([
            'invoice_url' => $additionalInformation['iugu_payment']['url']
        ]);

        return parent::_toHtml(); // TODO: Change the autogenerated stub
    }
}
